language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE query_ai_test;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('Chillduck56!') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - ENVIRONMENT=test pytest tests/